title: 'Dex-Pump | Improving Value from Mature Horizontal Wells'
description: 'Dex-Pump is an oil field solution that prolongs the life of rod-pumped horizontal wells by extending the pumping system's intake deep into the curve, removing backpressure on the reservoir.'
show_downloads: false
google_analytics:
theme: jekyll-theme-architect